import {useEffect,useMemo,useState} from 'react';
import {LogOut,Save,Plus,Trash2,Edit3,ArrowLeft,Settings,Hotel,CalendarCheck,Images,HelpCircle,Utensils,Tag,LayoutDashboard} from 'lucide-react';
import {supabase} from './supabase';

type Tab='overview'|'settings'|'rooms'|'services'|'faqs'|'gallery'|'offers'|'bookings';
const tables:any={
 rooms:{table:'pano_rooms',title:'الغرف والأجنحة',fields:[
  ['name_ar','اسم الغرفة بالعربي','text'],['name_en','الاسم بالإنجليزية','text'],['tag','الوسم','text'],['meta_ar','الوصف المختصر بالعربي','text'],['meta_en','الوصف المختصر بالإنجليزية','text'],['description_ar','الوصف الكامل بالعربي','textarea'],['description_en','الوصف الكامل بالإنجليزية','textarea'],['image_url','رابط الصورة','text'],['features_ar','المميزات بالعربي (افصل بفاصلة)','array'],['features_en','المميزات بالإنجليزية (افصل بفاصلة)','array'],['price','السعر','number'],['discount_percent','الخصم %','number'],['is_published','ظاهر في الموقع','boolean'],['sort_order','الترتيب','number']]},
 services:{table:'pano_services',title:'الخدمات والمرافق',fields:[
  ['title_ar','العنوان بالعربي','text'],['title_en','العنوان بالإنجليزية','text'],['subtitle_ar','العنوان الفرعي بالعربي','text'],['subtitle_en','العنوان الفرعي بالإنجليزية','text'],['description_ar','الوصف بالعربي','textarea'],['description_en','الوصف بالإنجليزية','textarea'],['icon','اسم الأيقونة','text'],['image_url','رابط الصورة','text'],['is_published','ظاهر في الموقع','boolean'],['sort_order','الترتيب','number']]},
 faqs:{table:'pano_faqs',title:'الأسئلة الشائعة',fields:[
  ['question_ar','السؤال بالعربي','text'],['question_en','السؤال بالإنجليزية','text'],['answer_ar','الإجابة بالعربي','textarea'],['answer_en','الإجابة بالإنجليزية','textarea'],['is_published','ظاهر في الموقع','boolean'],['sort_order','الترتيب','number']]},
 gallery:{table:'pano_gallery',title:'المعرض',fields:[
  ['title_ar','العنوان بالعربي','text'],['title_en','العنوان بالإنجليزية','text'],['image_url','رابط الصورة','text'],['category','التصنيف','text'],['is_published','ظاهر في الموقع','boolean'],['sort_order','الترتيب','number']]},
 offers:{table:'pano_offers',title:'العروض والباقات',fields:[
  ['title_ar','العنوان بالعربي','text'],['title_en','العنوان بالإنجليزية','text'],['description_ar','الوصف بالعربي','textarea'],['description_en','الوصف بالإنجليزية','textarea'],['image_url','رابط الصورة','text'],['price','السعر','number'],['discount_percent','الخصم %','number'],['valid_from','من تاريخ','date'],['valid_to','إلى تاريخ','date'],['is_published','ظاهر في الموقع','boolean'],['sort_order','الترتيب','number']]}
};

const blank=(cfg:any)=>Object.fromEntries(cfg.fields.map((f:any)=>[f[0],f[2]==='boolean'?true:f[2]==='array'?[]:'']));
const display=(v:any,type:string)=>type==='array'?(v||[]).join(', '):type==='boolean'?(v?'نعم':'لا'):(v??'');

function Login({onLogin}:{onLogin:()=>void}) {
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:any)=>{e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError('بيانات الدخول غير صحيحة أو الحساب غير مخوّل.');else onLogin()};
 return <div className="admin-shell admin-login" dir="rtl"><div className="admin-login-card"><div className="admin-logo">PH</div><span className="admin-kicker">PANORAMA · CONTROL CENTER</span><h1>لوحة إدارة بانوراما</h1><p>تحكم كامل بالموقع والمحتوى والهوية والحجوزات.</p><form onSubmit={submit}><input type="email" required placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={busy}>{busy?'جارٍ الدخول…':'دخول آمن'}</button></form><small>يجب أن يكون حسابك مضافًا إلى pano_admins في Supabase.</small></div></div>
}

function Collection({cfg}:{cfg:any}) {
 const [items,setItems]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{setLoading(true);const {data}=await supabase.from(cfg.table).select('*').order('sort_order',{ascending:true});setItems(data||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const save=async()=>{setSaving(true);setMsg('');const payload={...editing};delete payload.id;delete payload.created_at;let q=editing.id?supabase.from(cfg.table).update(payload).eq('id',editing.id):supabase.from(cfg.table).insert(payload);const {error}=await q;setSaving(false);if(error)setMsg(error.message);else{setEditing(null);setMsg('تم الحفظ بنجاح');load()}};
 const remove=async(id:string)=>{if(!confirm('حذف هذا العنصر نهائيًا؟'))return;await supabase.from(cfg.table).delete().eq('id',id);load()};
 return <section className="admin-panel"><div className="admin-panel-head"><div><span className="admin-kicker">CONTENT MANAGER</span><h2>{cfg.title}</h2></div><button className="admin-primary small" onClick={()=>setEditing(blank(cfg))}><Plus size={16}/>إضافة جديد</button></div>{msg&&<div className="admin-success">{msg}</div>}{editing&&<div className="editor-card"><div className="editor-head"><h3>{editing.id?'تعديل العنصر':'إضافة عنصر جديد'}</h3><button onClick={()=>setEditing(null)}>إلغاء</button></div><div className="editor-grid">{cfg.fields.map((f:any)=><label key={f[0]} className={f[2]==='textarea'?'wide':''}><span>{f[1]}</span>{f[2]==='textarea'?<textarea rows={4} value={display(editing[f[0]],f[2])} onChange={e=>setEditing({...editing,[f[0]]:e.target.value})}/>:f[2]==='boolean'?<input type="checkbox" checked={!!editing[f[0]]} onChange={e=>setEditing({...editing,[f[0]]:e.target.checked})}/>:<input type={f[2]==='number'?'number':f[2]==='date'?'date':'text'} value={display(editing[f[0]],f[2])} onChange={e=>setEditing({...editing,[f[0]]:[...['array'].filter(x=>x===f[2])].length?e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean):f[2]==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/>}</label>)}</div><button className="admin-primary" onClick={save} disabled={saving}><Save size={16}/>{saving?'جارٍ الحفظ…':'حفظ التغييرات'}</button></div>}{loading?<p>جارٍ التحميل…</p>:<div className="admin-table-wrap"><table><thead><tr><th>العنصر</th><th>الحالة</th><th>الترتيب</th><th>إجراء</th></tr></thead><tbody>{items.map((it:any)=><tr key={it.id}><td><strong>{it.name_ar||it.title_ar||it.question_ar||it.category||'عنصر'}</strong></td><td><span className={it.is_published===false?'status off':'status'}>{it.is_published===false?'مخفي':'منشور'}</span></td><td>{it.sort_order??'-'}</td><td><button className="icon-btn" onClick={()=>setEditing(it)}><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>remove(it.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</section>
}

function SettingsPanel() {
 const fields:any[]=[
 ['hotel_name','اسم الفندق','text'],['site_name_en','اسم الفندق بالإنجليزية','text'],['logo_url','رابط الشعار','text'],['logo_alt','وصف الشعار','text'],['favicon_url','رابط الأيقونة','text'],['phone_primary','الهاتف الرئيسي','text'],['phone_secondary','الهاتف الثاني','text'],['email','البريد الإلكتروني','text'],['whatsapp','واتساب','text'],['address_ar','العنوان بالعربي','text'],['address_en','العنوان بالإنجليزية','text'],['map_url','رابط Google Maps','text'],['booking_url','رابط الحجز الخارجي (اختياري)','text'],['social_instagram','Instagram','text'],['social_facebook','Facebook','text'],['social_tiktok','TikTok','text'],['social_x','X / Twitter','text'],['hero_title_ar','عنوان الواجهة بالعربي','textarea'],['hero_title_en','عنوان الواجهة بالإنجليزية','textarea'],['hero_description_ar','وصف الواجهة بالعربي','textarea'],['hero_description_en','وصف الواجهة بالإنجليزية','textarea'],['hero_image_url','صورة الواجهة','text'],['primary_color','اللون الأساسي','color'],['secondary_color','اللون الثانوي','color'],['background_color','لون الخلفية','color'],['accent_color','لون التمييز','color'],['font_heading','خط العناوين','text'],['font_body','خط النص','text'],['meta_title_ar','SEO عنوان عربي','text'],['meta_title_en','SEO عنوان إنجليزي','text'],['meta_description_ar','SEO وصف عربي','textarea'],['meta_description_en','SEO وصف إنجليزي','textarea'],['footer_text_ar','نص التذييل بالعربي','textarea'],['footer_text_en','نص التذييل بالإنجليزية','textarea'],['show_reviews','إظهار التقييمات','boolean'],['show_offers','إظهار العروض','boolean'],['show_gallery','إظهار المعرض','boolean'],['maintenance_mode','وضع الصيانة','boolean']];
 const [data,setData]=useState<any>({}),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{supabase.from('pano_site_settings').select('*').eq('id',true).single().then(({data})=>setData(data||{}))},[]);
 const save=async()=>{setSaving(true);const {error}=await supabase.from('pano_site_settings').update({...data,updated_at:new Date().toISOString()}).eq('id',true);setSaving(false);setMsg(error?error.message:'تم حفظ هوية وإعدادات الموقع');};
 return <section className="admin-panel"><div className="admin-panel-head"><div><span className="admin-kicker">SITE CONTROL</span><h2>الهوية والإعدادات الشاملة</h2></div><button className="admin-primary small" onClick={save}><Save size={16}/>حفظ الكل</button></div>{msg&&<div className="admin-success">{msg}</div>}<div className="settings-grid">{fields.map(f=><label key={f[0]} className={f[2]==='textarea'?'wide':''}><span>{f[1]}</span>{f[2]==='textarea'?<textarea rows={3} value={data[f[0]]||''} onChange={e=>setData({...data,[f[0]]:e.target.value})}/>:f[2]==='boolean'?<input type="checkbox" checked={!!data[f[0]]} onChange={e=>setData({...data,[f[0]]:e.target.checked})}/>:<input type={f[2]==='color'?'color':'text'} value={data[f[0]]||''} onChange={e=>setData({...data,[f[0]]:e.target.value})}/>}</label>)}</div></section>
}

function Bookings() {
 const [rows,setRows]=useState<any[]>([]);
 const load=async()=>{const {data}=await supabase.from('pano_bookings').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{load()},[]);
 const status=async(id:string,v:string)=>{await supabase.from('pano_bookings').update({status:v}).eq('id',id);load()};
 return <section className="admin-panel"><div className="admin-panel-head"><div><span className="admin-kicker">RESERVATIONS</span><h2>طلبات الحجز</h2></div></div><div className="admin-table-wrap"><table><thead><tr><th>الضيف</th><th>الهاتف</th><th>التاريخ</th><th>الغرفة</th><th>الحالة</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.guest_name}</td><td>{r.phone}</td><td>{r.check_in} → {r.check_out}</td><td>{r.room_name}</td><td><select value={r.status||'new'} onChange={e=>status(r.id,e.target.value)}><option value="new">جديد</option><option value="confirmed">مؤكد</option><option value="pending">معلّق</option><option value="cancelled">ملغي</option><option value="completed">مكتمل</option></select></td></tr>)}</tbody></table></div></section>
}

export default function Admin(){
 const [session,setSession]=useState<any>(null),[tab,setTab]=useState<Tab>('overview');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const [allowed,setAllowed]=useState<boolean|null>(null);
 useEffect(()=>{if(!session){setAllowed(null);return}supabase.from('pano_admins').select('user_id').eq('user_id',session.user.id).maybeSingle().then(({data})=>setAllowed(!!data))},[session]);
 if(!session)return <Login onLogin={()=>{}}/>;
 if(allowed===null)return <div className="admin-loading">جارٍ التحقق من صلاحيات المدير…</div>;
 if(!allowed)return <div className="admin-shell admin-login" dir="rtl"><div className="admin-login-card"><div className="admin-logo">!</div><h1>لا توجد صلاحية</h1><p>حسابك مسجل الدخول، لكنه ليس ضمن مديري بانوراما.</p><button className="admin-primary" onClick={()=>supabase.auth.signOut()}>تسجيل الخروج</button></div></div>;
 const nav:any[]=[['overview','نظرة عامة',LayoutDashboard],['settings','هوية الموقع',Settings],['rooms','الغرف والأجنحة',Hotel],['services','الخدمات',Utensils],['faqs','الأسئلة',HelpCircle],['gallery','المعرض',Images],['offers','العروض',Tag],['bookings','الحجوزات',CalendarCheck]];
 return <div className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><span>PH</span><div><b>PANORAMA</b><small>CONTROL CENTER</small></div></div><div className="admin-nav">{nav.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id as Tab)} key={id}><Icon size={17}/>{label}</button>)}</div><button className="admin-logout" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/>خروج</button></aside><main className="admin-main"><header className="admin-top"><div><span className="admin-kicker">PANORAMA HOTEL ADEN</span><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><a href="/" className="view-site">عرض الموقع <ArrowLeft size={15}/></a></header>{tab==='overview'?<section className="admin-overview"><div className="overview-card"><CalendarCheck/><b>الحجوزات</b><span>راجع الطلبات وغيّر حالتها من هنا.</span><button onClick={()=>setTab('bookings')}>فتح الحجوزات</button></div><div className="overview-card"><Settings/><b>كل شيء قابل للتعديل</b><span>الاسم والشعار والألوان والتواصل والصفحات والمحتوى.</span><button onClick={()=>setTab('settings')}>إدارة الهوية</button></div><div className="overview-card"><Hotel/><b>المحتوى</b><span>أضف واحذف وعدّل الغرف والخدمات والأسئلة والعروض والصور.</span><button onClick={()=>setTab('rooms')}>إدارة المحتوى</button></div></section>:tab==='settings'?<SettingsPanel/>:tab==='bookings'?<Bookings/>:<Collection cfg={tables[tab]}/>}</main></div>
}
