import {useState} from 'react';
import {Menu,X,ArrowRight,CalendarDays,Users,Check,MapPin,Phone,Mail} from 'lucide-react';
const rooms=[['Aurelia Suite','120 m²','420','https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=85'],['Garden Room','48 m²','210','https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=85'],['Pool Residence','86 m²','330','https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1400&q=85']];
function Booking({close}:{close:()=>void}){const [done,setDone]=useState(false);return <div className="modal" onMouseDown={close}><div className="booking-modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}><X/></button>{done?<div className="success"><Check size={44}/><h2>Request received.</h2><p>Our reservations team will confirm your stay shortly.</p><button className="primary" onClick={close}>Done</button></div>:<><span className="eyebrow">Reservations</span><h2>Plan your stay.</h2><div className="fields"><label>Check in<input type="date"/></label><label>Check out<input type="date"/></label><label>Guests<select><option>2 adults</option><option>1 adult</option><option>3 adults</option></select></label><label>Room<select>{rooms.map(r=><option key={r[0]}>{r[0]}</option>)}</select></label></div><button className="primary wide" onClick={()=>setDone(true)}>Check availability <ArrowRight size={16}/></button><p className="fine">No payment is taken at this stage.</p></>}</div></div>}
export default function App(){const[menu,setMenu]=useState(false),[booking,setBooking]=useState(false),[room,setRoom]=useState<string[]|null>(null),[faq,setFaq]=useState(-1);return <div className="site"><header><a className="logo" href="#top">AURELIA<small>HOTEL & RESIDENCES</small></a><nav className={menu?'show':''}><a href="#stay" onClick={()=>setMenu(false)}>Stay</a><a href="#experience" onClick={()=>setMenu(false)}>Experience</a><a href="#dining" onClick={()=>setMenu(false)}>Dining</a><a href="#story" onClick={()=>setMenu(false)}>Story</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><button className="nav-book" onClick={()=>setBooking(true)}>Book your stay</button><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><main id="top">
<section className="hero"><div className="shade"/><div className="hero-copy"><span className="eyebrow light">A considered stay · since 1987</span><h1>Luxury, with room to breathe.</h1><p>A quiet coastal retreat shaped by warm light, thoughtful architecture and unhurried hospitality.</p><div className="actions"><button className="light" onClick={()=>setBooking(true)}>Reserve a room <ArrowRight size={17}/></button><a href="#story">Discover our story</a></div></div><span className="caption">THE COAST · YOUR PRIVATE ESCAPE</span></section>
<section className="availability"><div><CalendarDays/><small>Check in</small><b>Choose a date</b></div><div><CalendarDays/><small>Check out</small><b>Choose a date</b></div><div><Users/><small>Guests</small><b>2 adults</b></div><button onClick={()=>setBooking(true)}>Check availability <ArrowRight size={16}/></button></section>
<section className="section intro" id="story"><div><span className="eyebrow">The Aurelia feeling</span><h2>Some places ask you to slow down.</h2></div><div><p className="lead">Aurelia is designed around a simple idea: the most memorable luxury is rarely loud.</p><p>It lives in the morning light, the details you notice twice, and the feeling of being completely looked after.</p><a className="link" href="#experience">Explore the experience <ArrowRight size={16}/></a></div></section>
<div className="marquee"><span>24-hour concierge</span><span>Complimentary Wi-Fi</span><span>Breakfast daily</span><span>Wellness & spa</span></div>
<section className="section" id="stay"><div className="head"><div><span className="eyebrow">Stay beautifully</span><h2>Rooms & residences</h2></div><p>Three ways to stay, each with the same quiet attention to detail.</p></div><div className="rooms">{rooms.map(r=><article key={r[0]}><div className="room-img"><img src={r[3]} alt={r[0]}/><span>Signature</span><button onClick={()=>setRoom(r)}>View room <ArrowRight size={14}/></button></div><div className="room-body"><div><h3>{r[0]}</h3><p>{r[1]} · King bed · Thoughtful amenities</p></div><strong>{'$'+r[2]}<small> / night</small></strong></div></article>)}</div></section>
<section className="feature" id="experience"><div className="feature-img"/><div className="feature-copy"><span className="eyebrow">The ritual</span><h2>Wellness without a schedule.</h2><p>Begin with a slow morning swim. Follow it with a treatment, a shaded lunch and an afternoon with nowhere to be.</p><ul><li><Check/>Private spa & treatment rooms</li><li><Check/>Heated infinity pool</li><li><Check/>Movement studio & garden</li></ul><a className="link light-link" href="#contact">Plan your experience <ArrowRight size={16}/></a></div></section>
<section className="section dining" id="dining"><div className="dining-img"/><div><span className="eyebrow">Dining at Aurelia</span><h2>Local ingredients. Unhurried evenings.</h2><p>Our kitchen follows the seasons, working with nearby growers and fishermen to create food that feels generous, precise and unmistakably of this place.</p><a className="link" href="#contact">Discover dining <ArrowRight size={16}/></a></div></section>
<section className="quote"><span>“</span><blockquote>Hospitality is not something we add to the stay. It is the stay.</blockquote><small>— The Aurelia House</small></section>
<section className="section faq"><div><span className="eyebrow">Good to know</span><h2>Before you arrive.</h2></div><div>{['What time is check-in and check-out?','Is breakfast included?','Can I arrange airport transfers?','Do you accommodate private events?'].map((q,i)=><div className="faq-row" key={q}><button onClick={()=>setFaq(faq===i?-1:i)}>{q}<span>{faq===i?'−':'+'}</span></button>{faq===i&&<p>Our concierge team will arrange the details for you. Contact us before arrival and we will tailor everything to your stay.</p>}</div>)}</div></section>
<section className="cta"><div><span className="eyebrow light">Your time, considered</span><h2>Make space for something memorable.</h2></div><button className="light" onClick={()=>setBooking(true)}>Book your stay <ArrowRight size={17}/></button></section></main>
<footer id="contact"><div className="footer-main"><div><div className="logo white">AURELIA<small>HOTEL & RESIDENCES</small></div><p>A quiet retreat for curious travelers, slow mornings and beautiful evenings.</p></div><div className="contact"><b>Contact</b><span><MapPin/>Coastal Road, Aurelia</span><span><Phone/>+00 000 000 000</span><span><Mail/>stay@aurelia.example</span></div></div><div className="footer-bottom">© 2026 Aurelia Hotel & Residences <span>Privacy · Terms</span></div></footer>
{booking&&<Booking close={()=>setBooking(false)}/>} {room&&<div className="modal" onMouseDown={()=>setRoom(null)}><div className="room-modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setRoom(null)}><X/></button><img src={room[3]} alt={room[0]}/><div><span className="eyebrow">Signature stay</span><h2>{room[0]}</h2><p>A considered private retreat with natural textures, generous space and attentive details.</p><ul><li><Check/> {room[1]} of space</li><li><Check/> King bed</li><li><Check/> Daily breakfast</li></ul><button className="primary" onClick={()=>{setRoom(null);setBooking(true)}}>Reserve this room <ArrowRight size={16}/></button></div></div></div>}</div>}